### ISSUE TITLE
doesnt work with basic rigify "copy chain" bones

### ISSUE THREAD

**Issue by AnityEx** [Pauan/blender-rigid-body-bones#5]
I've tried apply this to a rigify generated rig and the most basic bone type is this wich makes just a bone controller over a normal bone, doesn't work

**Comment by Pauan** [comment]
Of course you cannot use an `Active` rigid body with a bone controller... because the rigid body would be fighting with the controller: which one should be in control of the bone?

The point of `Active` rigid bodies is that they are entirely controlled by the rigid body simulation, they cannot be controlled by you. If you want to be in control of the bones, then you must use `Passive` rigid bodies.

So if you want to use `Active` rigid bodies, then you must make sure that the bone is not controlled by something else (like a controller or constraint).

And of course you can combine `Passive` and `Active` rigid bodies in the same rig, that is completely fine.

**Comment by AnityEx** [comment]
understandable thanks a lot

**Comment by Pauan** [comment]
I just released [version 1.6.0](https://github.com/Pauan/blender-rigid-body-bones/releases/tag/v1.6.0). You can now create constraints between bones, which means that IK can now work with `Active` bones. See the `examples/IK.blend` file for an example.

So let's say you wanted to make the Rigify arm bones `Active`. You would follow these steps:

* Go into Edit mode and remove the parent from the hand bone (`DEF-hand.L`)
* Go into Pose mode and make the arm bones `Active`
* On the hand bone (`DEF-hand.L`) add a Constraint, and make the target `DEF-forearm.L.001`

Now the hand will act like an IK, so the arm will follow the hand (even though it is `Active`).

Here is a [`Rigify.blend`](https://github.com/Pauan/blender-rigid-body-bones/files/6423978/Rigify.zip) file as an example. You can simply open it and play the animation.
