### ISSUE TITLE
Weird unintended scaling effect. 

### ISSUE THREAD

**Issue by DubiousHam** [Pauan/blender-rigid-body-bones#7]
Heya!
love the addon! huge time saver. 

but I've had an issue recently.
when switching between pose and object mode, the bones on her ears will Scale and distort oddly. almost as if there Parent object has been scaled or skewed. 

![770fc440606596664e4ab9ec2db430ac](https://user-images.githubusercontent.com/84322837/118481630-af4eb580-b6e1-11eb-9c6c-507c7a2edd70.gif)

i can't seem to find the parent of the rigidbody joint to see if thats the case. and even if i did, any fixes i make would just be undone  by the addon itself i imagine. 

i haven't scaled any one of her control bones.
there isn't really an animation yet, so that can't be an issue.
it is my understanding that you can move and rotate the Active bones around. only on frame 1.  but i suspect that might be the source of the issue here.

any idea what I'm doing wrong here?

also have ya ever thought about putting this up on some market place so we can support the development of the addon financially?

**Comment by Pauan** [comment]
I haven't run into that problem on any of my projects. Could you please attach your `.blend` file? That would make it a lot easier for me to find the problem. You can cleanup any unnecessary things if you want.

**Comment by Pauan** [comment]
Okay, so there's two issues here:

1. You have a bunch of errors, because a non-Active bone cannot have an Active parent. It shows you in the Armature panel which bones are wrong.

   You can fix it by either making those bones Active, or by changing their parent (so they are no longer a child of an Active bone).

   If you change the parent, then the child bone will no longer influence its old parent. If you still want it to influence the parent, you can use the Constraints panel to create a constraint between the two bones. You can see the `IK.blend` or `Constraints.blend` examples for how to do this.

2. Even after fixing the broken bones, the scale issue was still there. There was a minor bug with the bone matrixes, I have fixed that with [version 1.6.1](https://github.com/Pauan/blender-rigid-body-bones/releases/tag/v1.6.1), thanks for the report.

**Comment by DubiousHam** [comment]
thanks so much! 

oh right! 
yeah i couldn't find any documentation on what those errors in the panel meant. 
yeah now that ya mention it yah i had some fluff control bones on her ears 🤔  

but that wasn't the cause of my specific issue? 

so just for future reference, what errors occur by having a non active bone be the child of an active bone? 

i can't really notice any errors caused by it myself. but i may just be ignorant.

**Comment by Pauan** [comment]
In the Rigid Body panel it will say `Children of Active must be Active` for the incorrect bones. Unfortunately it can't explain in detail, because it has to fit in a small panel.

The reason you can't have non-Active children is because that will cause a circular dependency in Blender (because the Active parent automatically moves, which then moves the child, but the child isn't Active so it can't move).

So when the addon detects that situation, it disables the child bone. That fixes the circular dependency, but it means the child bone won't behave properly.

> but that wasn't the cause of my specific issue?

That's correct, [the add-on was incorrectly applying the bone's parent matrix](https://github.com/Pauan/blender-rigid-body-bones/commit/b7142c0e1c842687779865ff1c9193119b0cf0db#diff-17f360b7cfffdd95031db3dda21be00d799d5692712feb61e0f10b8e512a4615R441-R447). This only happens in extremely rare situations, which is why I hadn't noticed it before (even after a lot of testing).

**Comment by DubiousHam** [comment]
ah! so basically. i hadn't noticed an issues with that because i haven't had to  animate in a situation where that was the case.
i would have noticed an issue the second i tried to use those floof controls. 
Gotcha! 
Thanks again man!
